- src/__tests__/components/pages/FAQsPage.test.jsx
- src/components/elements/AppRoutes.jsx
- src/components/elements/Footer.jsx
- src/components/pages/FAQsPage.jsx
- src/styles/forms.js
This pull request (PR) solves the issue of implementing the faqs page (Issue [#31]).
What kind of change does this PR introduce?
This PR introduces the faqs info
Does this PR introduce a breaking change?
No
What needs to be documented once your changes are merged?
Unsure
> Implement FAQs Page

- src/components/pages/WeeklyDigestPage.jsx
- src/styles/forms.js
**What kind of change does this PR introduce?**
This PR implements the weekly digest subscription page 
**Does this PR introduce a breaking change?**
Unsure
**What needs to be documented once your changes are merged?**
Unsure
> Implement weekly digest page

- src/components/elements/Footer.jsx
- src/components/pages/FAQsPage.jsx
Design polish for FAQs page
Before:
After:
> Adjust FAQ page styling

- src/__tests__/components/pages/PrivacyPage.test.jsx
- src/components/elements/AppRoutes.jsx
- src/components/elements/Footer.jsx
- src/components/pages/PrivacyPolicyPage.jsx
- src/styles/privacy.js
#55 
Creating a placeholder for the privacy page.
> Implement privacy policy page

- src/components/elements/AppRoutes.jsx
- src/components/pages/CodeOfConductPage.jsx
- src/styles/conduct.js
> Implement code of conduct page

- src/App.js
- src/components/elements/FeaturedEvents.jsx
- src/components/elements/IntroductionSection.jsx
- src/components/elements/NavigationBar.jsx
- src/components/elements/SearchEvents.jsx
- src/components/elements/SearchResultViewSelector.js
- src/hooks/useDarkmode.js
- src/styles/forms.js
- tailwind.config.js
Hello,
I've implemented a working dark mode for the home page only. I would like feedback on the colors during dark mode and also if I should apply dark mode to every other page.
> Implemented a dark mode feature(Home page only)

- src/App.js
- src/components/elements/DownArrowIcon.jsx
- src/components/elements/DropdownMenu.jsx
- src/components/elements/EventCalendarView.jsx
- src/components/elements/EventGridView.jsx
- src/components/elements/NavigationBar.jsx
- src/components/elements/PageLoader.jsx
- src/components/elements/SearchEvents.jsx
- src/components/pages/ConfirmRegistrationPage.jsx
- src/components/pages/EventPage.jsx
- src/components/pages/HomePage.jsx
- src/hooks/dark-mode.js
- src/hooks/events.js
- src/styles/navbar.js
- src/utils/strings.js
This PR includes a handful of styles fixes and bug fixes from a review of the UI we have so far.
> Several style fixes and bug fixes.

- src/App.js
- src/components/elements/EditEventButton.jsx
- src/components/elements/EventForm.jsx
- src/components/elements/ReviewEventMainSection.jsx
- src/components/pages/EventPage.jsx
- src/hooks/events.js
> Apply basic author permissions.

- .github/config.yml
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
Towards #103 
Towards #100 
Closes #101
> set up welcome bot, CoC, contributing template

- package-lock.json
- package.json
- src/App.js
Install GA package following guidelines from https://github.com/react-ga/react-ga with issue ticket's id.
> Install GA tracking package

- src/__tests__/components/pages/EventCalendarPage.test.jsx
- src/components/elements/EventCalendarView.jsx
- src/components/elements/EventListView.jsx
- src/components/elements/RegionField.jsx
- src/components/elements/SearchForm.jsx
- src/components/pages/EventCalendarPage.jsx
- src/constants/events.js
- src/hooks/events.js
- src/utils/events.js
This PR implements changes to address https://github.com/data-umbrella/event-board-web/issues/13.
Wires up the event search form to work with the event calendar. Also, adds the event list to the bottom. The display and user experience of the calendar using the plugin we have is rough. We will need to discuss what functionality is needed for mobile calendar. For now, I am just rendering the event list grouped by month (which also need mobile design polish).
Before:
Desktop 
Mobile
After:
Desktop
Mobile
> Wire up event calendar page

- src/components/elements/Footer.jsx
- tailwind.config.js
Cleanup footer ( if a page doesn't exist do _not_ include a link to that page).
[Figma Link](https://docs.google.com/spreadsheets/d/1eQEHbXN7NU7G2RE4qLC9A3bjJ_xcqSYHH05H-Pj5ank/edit#gid=0)
Fixes #154 
-Imported logo color image
-Adjusted for mobile vs. desktop
Before:
Desktop:
Mobile:
After:
Desktop:
Mobile:
> Feat/154 Footer

- src/components/elements/AppRoutes.jsx
- src/components/pages/TermsPage.jsx
- src/styles/terms.js
Fixes #142
[Figma Link] https://www.figma.com/file/rs7dsdmKlxdfuQ0wobp5B2/Data-Umbrella?node-id=1457%3A3579
No left side navigation on first iteration, just do the Terms of service, squared with the page title, inherit padding from page.
Before:
(Page was not present from main branch)
After:
Before:
Edit space between left-side navigation and main section then updated spaces for privacy and code of conduct links.
After:
Before: 
After:
> Add Terms and Conditions Page and Styles 

- src/components/elements/AppRoutes.jsx
- src/components/elements/Footer.jsx
- src/components/elements/SignUpForm.jsx
- src/components/pages/SignUpPage.jsx
PR for #141 
Signup page has minor cleanup that needs to be done:
Before:
After:
Before:
Add link to terms page
After:
Small fix for mobile view
Before:
After:
> Update Sign Up Page

- CONTRIBUTING.md
- README.md
- move contributing instructions from README.md to CONTRIBUTING.md
- 
N/A
cc:  @symeneses
> mv contributing instructions+ update

- public/index.html
- src/App.js
- src/components/elements/AppRoutes.jsx
Added ga tag manually and use location to listen to route changes for ga, this is as spartan as it gets, more context can be added later.
This was tested locally and requires knowledge of google analytics and react routing/location hook.
> Added ga tag manually and use location to listen to route changes

- src/components/elements/SignInForm.jsx
- src/components/pages/SignInPage.jsx
- src/index.css
Fixes #151
Minor style changes, if features missing or link to a page that doesn't exist, remove it until that feature/page has been created
- [ x] "No Account?" & "Sign U -->" not aligned at opposite ends of container
- [ x] Should there be a hover option for Sign Up link?- yes, added 
- [ x] Centering for email field and login button not aligned with logo/welcome back header
- [ x] Dark mode login button background does not reflect  #9747FF purple
- [ x] Dark mode text color change not reflected
- [ x] Sign In Pop Up - missing component -yes, addressed in separate ticket
- [ x] Mobile - Heading needs to be taken out
- [x ] Mobile - Username option not included in form. Also not included in desktop display figma (Figma updated to delete Username)
- [x ] Mobile - figma has no option for …
> Sign In page refactor

- src/components/elements/CategoryField.jsx
- src/components/elements/EventTypeField.jsx
- src/components/elements/LanguageField.jsx
- src/components/elements/PriceField.jsx
- src/components/elements/RegionField.jsx
- src/components/elements/SearchForm.jsx
- src/styles/forms.js
- tailwind.config.js
Search and Filters needs cleanup, focus should not be on functionality, but designing a component that
renders visually correct.
[Figma Link](https://www.figma.com/file/rs7dsdmKlxdfuQ0wobp5B2/Data-Umbrella?node-id=1457%3A4580)
padding should use tailwinds padding modifers, px, py, etc 
Desktop Light -
Desktop Dark -
Mobile - 
Desktop Light-
Desktop Dark -
Mobile-
> Issue #136 Search and Filter Issue

- package-lock.json
- package.json
- src/__tests__/elements/ReviewEventMainSection.test.jsx
- src/components/elements/CategoryField.jsx
- src/components/elements/EventTopicField.jsx
- src/components/elements/SearchForm.jsx
- src/components/elements/SocialMediaField.jsx
- src/hooks/events.js
- src/services/events.js
N/A
A couple of the filters were not fully wired up. This PR refactors how we build the filters and temporarily removes the topic field until we discuss what we want to do for topics since they are not include in the seed data. Installed the query string library for simplifying building query params.
This change only removed the topic field temporarily and has no other visual changes. It does not change the design or layout in a meaningful way. Going to opt to skip the screenshots.
> Add missing filters

- src/components/pages/FAQsPage.jsx
- src/components/pages/PrivacyPolicyPage.jsx
Added dark mode text support on FAQ & Privacy Policy pages.
Before:
After:
> Quick PR finished - added dark mode text support

- src/__tests__/components/pages/EventCalendarPage.test.jsx
- src/components/elements/EventsForMonth.jsx
- src/components/elements/LanguageField.jsx
- src/components/elements/RegionField.jsx
- src/components/elements/SearchEvents.jsx
- src/components/elements/SearchForm.jsx
- src/components/elements/SearchResultViewSelector.js
- src/components/pages/EditEventPage.jsx
- src/components/pages/EventCalendarPage.jsx
- src/constants/languages.js
- src/index.css
- src/styles/forms.js
- tailwind.config.js
No ticket
Handful of design polish changes to the event form and event search results.
Before:
Mobile
Desktop
After:
Mobile
Deskop
> Search events design polish

- src/components/elements/AboutUs.jsx
- src/components/elements/Contributor.jsx
No ticket associated with this PR.
Fixed small visual bug with contributor headshots not aligning.
Before:
After:
> About us page design polish.

- src/components/pages/WeeklyDigestPage.jsx
- src/styles/forms.js
Fixes #196 
Mobile has a bit of extra space above div, but still waiting on search component so it won't seem so drastic with the flexbox justification.
Before:
After:
> Added responsiveness across screens, incl. iPad. Done.

- src/components/elements/Footer.jsx
Fixes #107 
Added social icons to footer for desktop.
Before:
After:
> Added social icons to footer for desktop

- src/__tests__/components/pages/VerifyMagicLinkPage.test.jsx
- src/components/pages/HomePage.jsx
- src/components/pages/VerifyMagicLinkPage.jsx
- src/hooks/authentication.js
- src/index.js
No ticket. General code clean up and improvements.
Continuing to clean up the auth flow to prevent flakiness. Removes dependence on local storage for temporarily storing the users email.
No UI changes for this PR.
> Clean up auth flow.

- src/components/elements/DatePickerField.jsx
- src/components/elements/EventForm.jsx
- src/components/elements/EventTopicField.jsx
- src/components/elements/EventTypeField.jsx
- src/components/elements/LanguageField.jsx
- src/components/elements/PopularSearches.jsx
- src/components/elements/PriceField.jsx
- src/components/elements/RegionField.jsx
- src/components/elements/SearchForm.jsx
- src/constants/dates.js
- src/constants/events.js
- src/constants/languages.js
- src/hooks/events.js
- src/services/events.js
https://github.com/data-umbrella/event-board-web/issues/207
Handful of changes to work with updates on the backend to handle basic search functionality
No new visual changes besides hiding some elements. Design does not fundamentally change.
> Normalize search functionality

- src/components/elements/Footer.jsx
- src/components/elements/MobileNav.jsx
- src/components/pages/ContactPage.jsx
#209
Temporarily hide links to pages that are a work in progress and missing finalized content.
Before:
After:
> Hide links to WIP pages.

- src/components/elements/EventTopicField.jsx
- src/components/elements/EventTypeField.jsx
- src/components/elements/PriceField.jsx
- src/constants/events.js
- src/services/events.js
No ticket for this issue.
Fixing mismatch with back end column name.
N/A
> Clean up topic filter logic.

- public/index.html
- src/components/elements/AppRoutes.jsx
No ticket
Testing a hot fix for getting GA tracking working.
No UI changes for this PR.
> Update GA tracking id.

- src/__tests__/components/pages/EventCalendarPage.test.jsx
Correct Event Calendar Pages test error
EventCalendarPage.test.jsx
n/a
Before:
After:
> Fix calendar test error dates

- src/App.js
Fixes #233 
-Adjusted hex color in App.js
-Added border to Contents section in App.js
Before:
After:
> Issue 233 Update Dark Mode Color and Footer Border

- src/components/elements/SearchResultViewSelector.js
- tailwind.config.js
Fixes #231 
Corrects the text color look for dark mode. 
Changes made in SearchResultViewSelector.js and tailwind.config.js
Before:
After:
> Dark Mode for Search Results View Buttons

- src/components/pages/ContactPage.jsx
- src/styles/forms.js
As per the [Figma](https://www.figma.com/file/rs7dsdmKlxdfuQ0wobp5B2/Data-Umbrella?node-id=1457%3A3680) file, the following changes need to be made in the Contact Page:
Update ContactPage.jsx, tailwind.config.js, forms.js
Before:
After:
> Issue 243 Contact Page Clean Up

- package-lock.json
- package.json
- src/index.js
- src/mirage.js
- src/services/authentication.js
No ticket
Adds fake API powered by [mirage.js](https://miragejs.com/). Simplify run the start command with the "dev" modifier 
```
npm run start:dev
```
> Add mirage for mocking out API calls in local development

- src/constants/languages.js
fixes #78 
Languages: All [Default], English, Espanol, Portuguese, Other
Before:
After:
> Issue 78 - Update Language Dropdown Options

- src/components/elements/NavigationBar.jsx
- src/constants/navbar.js
- src/styles/navbar.js
Fixes #228
Audit: https://docs.google.com/spreadsheets/d/1mfn1s6-ncwnaIYpDfD0OH1md6Ni2YB38N_qeyBZQwR8/edit#gid=464070281
Figma: https://www.figma.com/file/rs7dsdmKlxdfuQ0wobp5B2/Data-Umbrella?node-id=663%3A2513
Before:
After:
> Issue #228 : Clean Up Navbar styles

- src/components/elements/IntroductionSection.jsx
> Issue 227- Update darkmode for donate button 

- src/components/elements/EventForm.jsx
- src/components/elements/EventTypeField.jsx
fixes #34
Add (*) to indicate required fields
Before:
After:
> Issue 34: Add asterisks to Event Form

- src/components/elements/AboutUs.jsx
- src/components/elements/Contributor.jsx
- src/components/pages/AboutPage.jsx
fixes #226 and #99
Figma: https://www.figma.com/file/rs7dsdmKlxdfuQ0wobp5B2/Data-Umbrella?node-id=1457%3A3890
Audit: https://docs.google.com/spreadsheets/d/1mfn1s6-ncwnaIYpDfD0OH1md6Ni2YB38N_qeyBZQwR8/edit#gid=1849252639
Before:
After:
Before:
After:
> Issue 226: Update About Us Page styles

- src/components/elements/Footer.jsx
Fixes #254.
Change logo in the footer to match logo in the header.
Swapped the old logo for the new navbar logo and adjusted some of the styles.
Before:
After:
> Swapped old logo for the new logo and fixed the positioning.

- src/components/elements/EventGridView.jsx
> Update event grid view to 4 columns

- package-lock.json
- package.json
- src/App.css
- src/components/elements/SearchEventCard.jsx
- src/components/elements/SearchEvents.jsx
- src/components/elements/SpeakersField.jsx
- src/components/pages/HomePage.jsx
- src/hooks/events.js
- src/services/events.js
Adding pagination in the front end. Paired with Joe and Daniel.
Before:
After:
> Issue 258: Add pagination and styling in the front end

- src/components/pages/WeeklyDigestPage.jsx
- src/constants/urls.js
- src/services/weekly-digests.js
Fixes #160 
Before:
N/A
After:
> Issue #160 - Added weekly digests - API is receiving the digest email data.

- package-lock.json
- package.json
- src/components/pages/WeeklyDigestPage.jsx
- src/services/weekly-digests.js
Added the conditional rendering of the success component. If email exists, it'll display an error.
Before:
N/A
After:
https://user-images.githubusercontent.com/59852686/202013488-dae7b710-85da-407b-8aee-9710f756fadc.mov
> 271/ weekly digest guest user

- src/__tests__/components/pages/EventCalendarPage.test.jsx
- src/components/elements/EventPlanningDetail.jsx
- src/components/elements/EventPlanningSection.jsx
fixes #91 
Update EventPlanningDetail component to accept name for hyperlink.
Add name parameter to EventPlanningSection for Code of Conduct
Before:
After:
> Issue 91 - Update Code of Conduct URL

- src/components/elements/SearchEventCard.jsx
> Updated to fix broken images

- package-lock.json
- src/components/elements/FeaturedEvents.jsx
- src/components/elements/IntroductionSection.jsx
- src/components/elements/SearchEventCard.jsx
Fixes parts of #152:
- ~~Carousel section dots - specific design needed? (eg: fully gray bubbles?)~~ (design update not needed)
- ~~Mobile: Carousel is not needed for mobile view, should be refactored~~ (Ilia confirmed that carousel in mobile looked better)
-IntroductionSection.jsx - header needed size reformatting to reflect figma
-FeaturedEvents.jsx
Desktop - 
Mobile - 
After:
desktop-
mobile -
> Featured Events Carousel Clean UP (issue #152)

- package-lock.json
- package.json
- src/components/elements/EventForm.jsx
- src/components/elements/EventPlanningSection.jsx
- src/components/elements/EventTagsField.jsx
- src/constants/events.js
Fixes #264 
Figma: https://www.figma.com/file/rs7dsdmKlxdfuQ0wobp5B2/Data-Umbrella?node-id=0%3A1&t=UMMz4o13AxiwbL70-0
Before:
After:
> Issue 264: Add event tags to event submission form

- .eslintrc.js
- src/components/elements/EventForm.jsx
- src/components/elements/EventHashTags.jsx
- src/components/elements/EventHashtagField.jsx
- src/components/elements/EventPlanningSection.jsx
- src/components/pages/NewEventPage.jsx
- src/components/pages/ReviewEventPage.jsx
- src/constants/events.js
- src/services/api.js
Figma: https://www.figma.com/file/rs7dsdmKlxdfuQ0wobp5B2/Data-Umbrella?node-id=1457%3A5091
Fixes #265 
Before:
After:
**Note:** I had trouble with styling the input field to match the formik fields and adding pillboxes when "Enter" key is pressed. I took the same logic from SpeakerFiled for event hashtags. This data still needs to be added in the backend.
> Issue 265: Handle event hashtag input

- src/constants/api.js
- src/services/authentication.js
- src/utils/api.js
- src/utils/devices.js
- src/utils/sessions.js
https://github.com/data-umbrella/event-board-web/issues/260
Fix issues with HTTP only cookies on iOS causing issues for auth.
N/A
> Handle ios cookies issue.

- src/components/elements/MobileNav.jsx
- src/components/pages/MagicLinkSentPage.jsx
- src/services/authentication.js
- src/utils/api.js
No ticket. Found issue while testing.
Fixes issue with mobile nav where the sign in link shows when users are logged in. Also, fixes issue with variable scoping.
No desktop changes visible
Before:
After:
> Mobile nav auth fixes.

- src/mirage.js
No ticket for this pull request. Found this bug while testing locally.
Updated the mock API for pagination to mirror production.
There were not UI updates as part of this PR.
> Update mock api for pagination.

- src/services/authentication.js
- src/utils/api.js
Fix for issue introduced for web auth flow.
Using session storage for web and mobile for now. Need to research why httponly is not playing nicely with Django right now.
N/A
> Auth flow hot fix.

- src/components/elements/EventTopicField.jsx
- src/styles/forms.js
Fixes #290 
Fixes CSS of event topics selector
Before:
After:
> event topics css fix

- package-lock.json
- package.json
- src/__tests__/components/pages/EventCalendarPage.test.jsx
- src/__tests__/elements/EventForm.test.jsx
- src/components/elements/DatePickerField.jsx
- src/components/elements/EditEventButton.jsx
- src/components/elements/EventForm.jsx
- src/components/elements/EventPlanningSection.jsx
- src/components/elements/EventTagsField.jsx
- src/components/pages/ReviewEventPage.jsx
- src/constants/events.js
- src/hooks/dark-mode.js
- src/hooks/events.js
- src/services/events.js
- src/styles/forms.js
A bunch of miscellaneous clean up from testing this week.
> UI polish fixes

- CONTRIBUTING.md
> clean up Contributing file

- CONTRIBUTING.md
No ticket
Updated CONTRIBUTING instructions.
N/A
> Update CONTRIBUTING; node, nvm version info

- src/components/elements/Sponsors.jsx
Closes #335 
sponsors: temporarily comment out GOS
Before:
After:
> sponsors: temporarily comment out GOS

- CONTRIBUTING.md
Added a resource in the Contributing.md file
add resource for Django REST framework
NA
> added Django REST framework

- src/constants/events.js
-  Code
- Towards https://github.com/data-umbrella/event-board-web/issues/308
There is no default "All" for "Topics" field.
Added "All" in the "Topics" field
Before:
After:
> Add "All" option in the "Topics" field

- src/components/elements/IntroductionSection.jsx
Fixes #309
On the home page; Donate button; add an arrow indicating it is an external link
file:  event-board-web/src/components/elements/IntroductionSection.jsx
Before:
After:
> home page; Donate button; +arrow for external link

- src/components/elements/DatePickerField.jsx
- src/components/elements/EventForm.jsx
- src/components/elements/EventPlanningSection.jsx
- src/components/elements/SearchForm.jsx
- src/components/elements/TimeSlotField.jsx
- src/constants/dates.js
> Clean up date picker UX

- src/components/elements/SignInForm.jsx
- src/components/pages/SignInPage.jsx
It fixes #250 
Use the same classes that were in the signup form and page.
Before:
After:
> Apply same style/sizes of signup in signin

- .github/pull_request_template.md
discussion on template on PR #348 
Simplify PR template
Before:
After:
> simplify PR template

- bin/dev-api.json
- src/__tests__/elements/NavigationBar.test.jsx
- src/components/elements/AboutUs.jsx
- src/components/elements/Footer.jsx
- src/components/elements/NavigationBar.jsx
- src/constants/urls.js
> update DU url

- src/components/elements/ReviewEventMainSection.jsx
- src/components/pages/ReviewEventPage.jsx
@jtorreggiani Please review this as I can't test with dummy backend.
#342 
Enclosed div tag inside anchor tag.
No UI changes.
> Fixes Register Button on Event Page.

- src/components/elements/EventForm.jsx
- src/components/elements/FormErrors.jsx
- src/components/elements/ValidatedInput.jsx
- src/components/elements/ValidatedTextArea.jsx
- src/components/pages/ContactPage.jsx
Contact form did not reflect field requirements to submit. 
Note that Code of Conduct and Reference field will be updated with Issue #303 
Updated contact form inputs to use established validation component
Desktop:
Mobile:
Desktop:
Mobile:
> Contact Form Validations + Error Message

- src/components/pages/WeeklyDigestPage.jsx
- src/styles/forms.js
Adds email validation to Weekly Subscription
Before:
After:
> Issue 318:Email Format Validation

- src/__tests__/utils/price.test.js
- src/components/elements/SearchEventCard.jsx
- src/constants/events.js
- src/utils/strings.js
Update default price field to blank if neither Free or Selected is chosen
SearchEvent Card
Before:
After:
> Update price default

- package-lock.json
- package.json
- src/__tests__/components/pages/ReviewEventPage.test.jsx
- src/__tests__/elements/ReviewEventMainSection.test.jsx
- src/components/elements/EventCalendarView.jsx
- src/components/elements/EventForm.jsx
- src/components/elements/ReviewEventMainSection.jsx
- src/components/elements/ShareLinkIcon.jsx
- src/constants/events.js
- src/services/api.js
- src/styles/forms.js
Added social links and updated form, review, edit, and details components to reflect the social links change
- [ x] Fixes #296 
Adds social media icons
Adds event form section for adding links to share
simplified UI for adding, removing, updating links
Added links to details/review screen
Before:
After:
> Social Media Links/Sharing Links

- src/components/elements/ReviewEventMainSection.jsx
Correct null condition stemming from reviewing event
> Correct null condition

- src/components/elements/ReviewEventMainSection.jsx
- tailwind.config.js
Added to tailwind config, pulled color variants as advised by [tailwind docs](https://tailwindcss.com/docs/content-configuration#dynamic-class-names)
Before:
After:
> Issue 369: Event type color

- src/components/elements/EventForm.jsx
- src/components/elements/EventPriceField.jsx
- src/constants/events.js
Add option for event Price to Event Form
Added EventPrice component to event form, add constants
Before:
After:
> Event Form Price option

- CONTRIBUTING.md
- README.md
Towards #361 
Towards #393
- consistently use "Events Board"
- add Table of Contents to Contributing file
- add sub-section in Contributing for "return to work"
- add sub-section in Contributing for "debugging"
Before:
After:
> Update contributing guide (add TOC, return to work, debugging)

- src/constants/events.js
References:  
- PR in event-board-api https://github.com/data-umbrella/event-board-api/pull/103
- Issue in event-board-api https://github.com/data-umbrella/event-board-api/issues/53
1. use "canada-usa" instead of "usa-canda"
2. use "latin-america" instead of "latin-america-caribbean"
3. put regions in alphabetical order 
Before:
After:
> make regions consistent

- .github/FUNDING.yml
- enable repo-level GitHub sponsors
Before:
After:
> Create FUNDING.yml to enable repo-level Sponsors

- src/components/elements/SearchEvents.jsx
Refactored in SearchEvents.jsx
> Remove Calendar Pagination

- package-lock.json
Apply the non-breaking fixes from running `npm audit --fix`
Committing the changes to the package.json file from running `npm run audit fix`
N/A
+ Running `npm run audit --fix` will updates node modules
> Apply nonbreaking fixes from audit.

- src/components/elements/CustomDropdownMenu.jsx
- src/components/elements/NavigationBar.jsx
Setting styles for Dropdown menu for Profile/settings for consistency
Before:
After:
> fixing styling for profile dropdown menu

- CONTRIBUTING.md
> add link to installing node and nvm

- CONTRIBUTING.md
> update contributing instructions
